<?php
/** Front page — mirrors Home in src/routes/index.tsx. */
get_header();
$hero_image_id = absint( rjy_group_get_mod( 'rjy_hero_image' ) );
$hero_video_id = absint( rjy_group_get_mod( 'rjy_hero_video' ) );
$hero_poster = $hero_image_id ? wp_get_attachment_image_url( $hero_image_id, 'rjy-hero' ) : rjy_group_asset( 'hero-facilities-poster-unique.jpg' );
$hero_video = $hero_video_id ? wp_get_attachment_url( $hero_video_id ) : rjy_group_asset( 'rjy-hero.webm' );
$about_image_id = absint( rjy_group_get_mod( 'rjy_about_image' ) );
$about_image = $about_image_id ? wp_get_attachment_image_url( $about_image_id, 'full' ) : rjy_group_asset( 'company-service-integrity-unique.jpg' );
$stats = array( array( '20+', 'Years of experience', 'stat-experience-unique.jpg' ), array( '24/7', 'Critical response', 'stat-critical-response-unique.jpg' ), array( '5', 'Core industries', 'stat-core-industries-unique.jpg' ), array( '6', 'Integrated services', 'stat-integrated-services-unique.jpg' ) );
$values = array(
	array( 'shield-check', 'Compliance Expertise', 'Practical guidance shaped by controlled, high-accountability environments.', 'value-compliance-unique.jpg' ),
	array( 'users', 'Certified Team', 'Qualified specialists aligned around your facility and operating priorities.', 'value-certified-team-unique.jpg' ),
	array( 'clock3', 'Responsive Service', 'Clear communication and action when systems and schedules are under pressure.', 'value-responsive-service-unique.jpg' ),
	array( 'file-check-corner', 'Federal-Grade Standards', 'Disciplined documentation, safety, and delivery from scope through closeout.', 'value-federal-standards-unique.jpg' ),
);
?>
<section class="home-hero"><video class="home-hero-video" autoplay muted loop playsinline poster="<?php echo esc_url( $hero_poster ); ?>" aria-hidden="true"><source src="<?php echo esc_url( $hero_video ); ?>" type="video/webm"></video><img class="home-hero-fallback" src="<?php echo esc_url( $hero_poster ); ?>" alt="<?php esc_attr_e( 'Facilities engineers walking through a central utility plant', 'rjy-group' ); ?>" width="1600" height="900"><div class="home-hero-shade"></div><div class="site-container home-hero-content"><p class="eyebrow eyebrow-light"><?php echo esc_html( rjy_group_get_mod( 'rjy_hero_eyebrow', 'Integrated facility expertise' ) ); ?></p><h1><?php echo esc_html( rjy_group_get_mod( 'rjy_hero_title', 'Built for facilities that cannot stop.' ) ); ?></h1><p><?php echo esc_html( rjy_group_get_mod( 'rjy_hero_text', 'Reliable building systems, critical infrastructure, and operational technology support from one experienced team.' ) ); ?></p></div></section>
<section class="stats-bar"><div class="site-container"><?php foreach ( $stats as $stat ) : ?><div class="stat-panel"><img src="<?php echo rjy_group_asset( $stat[2] ); ?>" alt="" loading="lazy" width="992" height="672"><span class="stat-shade"></span><div><strong><?php echo esc_html( $stat[0] ); ?></strong><span><?php echo esc_html( $stat[1] ); ?></span></div></div><?php endforeach; ?></div></section>
<section class="page-section intro-band"><div class="site-container intro-grid"><div class="intro-copy"><?php rjy_group_section_head( __( 'Who we are', 'rjy-group' ), rjy_group_get_mod( 'rjy_about_heading', 'Delivering Service and Integrity' ), __( 'At RJY Group, we specialize in protecting and optimizing the systems that power essential facilities and infrastructure. We focus on maintaining the health and resilience of mission-critical systems that ensure your facility operates smoothly, efficiently, and securely. From Building Automation to Emergency Power Systems, our expert team provides reliable, cutting-edge solutions that guarantee long-term system performance and compliance with industry standards.', 'rjy-group' ) ); ?><div class="intro-facts"><div class="intro-badge"><?php echo rjy_group_icon( 'award' ); ?><span>RJY Group is a <strong>Service-Disabled Veteran-Owned Small Business</strong> (SDVOSB).</span></div><div class="intro-stat"><strong>16+</strong><span><?php esc_html_e( 'Years of experience in building automation, HVAC, and chiller maintenance, generator readiness, and smart building technologies.', 'rjy-group' ); ?></span></div></div></div><figure class="intro-image"><span class="intro-image-index">01 / SERVICE &amp; INTEGRITY</span><img src="<?php echo esc_url( $about_image ); ?>" alt="<?php esc_attr_e( 'Facilities specialists reviewing critical systems together', 'rjy-group' ); ?>" loading="lazy" width="1408" height="944"></figure></div></section>
<section class="page-section site-container"><?php rjy_group_section_head( __( 'Connected capabilities', 'rjy-group' ), rjy_group_get_mod( 'rjy_services_heading', 'One team across your building systems.' ), __( 'From controls and cooling to standby power and operational technology security, RJY Group helps reduce risk across the facility lifecycle.', 'rjy-group' ) ); rjy_group_tile_grid( 'services' ); ?><div class="section-link"><?php echo rjy_group_button_link( '/services', __( 'View all services', 'rjy-group' ), 'outline', 'default' ); ?></div></section>
<section class="page-section section-tint"><div class="site-container"><?php rjy_group_section_head( __( 'Industries', 'rjy-group' ), __( 'Built around demanding environments.', 'rjy-group' ), __( 'Purpose-built facility solutions that help healthcare, government, commercial, education, transportation, and utility organizations operate safely and reliably.', 'rjy-group' ) ); rjy_group_tile_grid( 'industries' ); ?><div class="section-link"><?php echo rjy_group_button_link( '/industries', __( 'Explore industries', 'rjy-group' ), 'outline', 'default' ); ?></div></div></section>
<section class="page-section site-container"><?php rjy_group_section_head( __( 'Why RJY Group', 'rjy-group' ), rjy_group_get_mod( 'rjy_testimonials_heading', 'A higher standard of facility partnership.' ) ); ?><div class="value-grid"><?php foreach ( $values as $value ) : ?><article><div class="value-image"><img src="<?php echo rjy_group_asset( $value[3] ); ?>" alt="" loading="lazy" width="992" height="672"></div><div class="value-copy"><?php echo rjy_group_icon( $value[0] ); ?><h3><?php echo esc_html( $value[1] ); ?></h3><p><?php echo esc_html( $value[2] ); ?></p></div></article><?php endforeach; ?></div></section>
<section class="cert-strip"><div class="site-container"><p><?php esc_html_e( 'Certifications & readiness', 'rjy-group' ); ?></p><span><?php echo rjy_group_icon( 'award' ); ?>SDVOSB</span><span><?php echo rjy_group_icon( 'building2' ); ?>GSA Capability</span><span><?php echo rjy_group_icon( 'map-pinned' ); ?>SAM.GOV Ready</span><span><?php echo rjy_group_icon( 'award' ); ?>ISO Aligned</span></div></section>
<section class="founder-section"><div class="site-container founder-inner"><div class="founder-copy"><p class="eyebrow eyebrow-light"><?php esc_html_e( 'Meet the founder', 'rjy-group' ); ?></p><h2>Richard J. Young</h2><p class="founder-lede"><?php esc_html_e( 'Founder & Director of RJY Group, a visionary leader dedicated to driving operational excellence in commercial facilities maintenance and cybersecurity compliance.', 'rjy-group' ); ?></p><p class="founder-body"><?php esc_html_e( 'Richard J. Young leads RJY Group with more than two decades across building automation, HVAC and chiller systems, emergency power readiness, and operational technology. A Service-Disabled Veteran and credentialed engineer (MSIS, M.Eng., PMP, CFM), he built the company on a simple standard: treat uptime as a promise, not a goal. That discipline shows up in every engagement through rigorous documentation, clear communication, and delivery that holds from first assessment to final closeout.', 'rjy-group' ); ?></p><?php echo rjy_group_button_link( '/about/founder', __( 'Meet Richard', 'rjy-group' ), 'default', 'lg', 'founder-cta' ); ?></div><figure class="founder-frame"><img src="<?php echo rjy_group_asset( 'richard-young-portrait.jpg' ); ?>" alt="<?php esc_attr_e( 'Richard J. Young, Founder and Director of RJY Group', 'rjy-group' ); ?>" loading="lazy" width="457" height="625"><figcaption><strong>Richard J. Young</strong><span>MSIS, M.Eng., PMP, CFM | Founder &amp; Director</span></figcaption></figure></div></section>
<?php rjy_group_articles(); rjy_group_cta_band(); ?>
<?php get_footer();
